openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/products":
    get:
      summary: Retrieves all products
      tags:
        - Products
      responses:
        "200":
          description: successful
servers:
  - url: https://acme-product-inventory-api.onrender.com
    description: Production server (Render)
  - url: http://localhost:3000
    description: Local development server
